# Generated by Django 4.2.4 on 2023-08-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
    migrations.CreateModel(
        name='Category',
        fields=[
            ('name', models.CharField(max_length=100, primary_key=True)),  # Set as primary key
            ('description', models.CharField(max_length=200)),
        ],
    ),
]
